include:
  - compose-mysql.yaml

name: yoga-app
services:

  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile-back
      target: run
    env_file: .env
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:${MYSQL_PORT:-3306}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true"
      spring.datasource.username: "${MYSQL_USER}"
      spring.datasource.password: "${MYSQL_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile-front
      target: run
    env_file: .env
    ports:
      - "${FRONT_END:-80}:80"
    depends_on:
      mysql:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - "./docker/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro"