version: '3.4'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: .env
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
    volumes:
      - "./ressources/sql/script.sql:/docker-entrypoint-initdb.d/1.sql:ro"

  adminer:
    image: adminer
    restart: always
    env_file: .env
    ports:
      - "${ADMINER_PORT:-9090}:8080"

  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile-back
      target: run
    env_file: .env
    ports:
      - "${TOMCAT_PORT:-8080}:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:${MYSQL_PORT:-3306}/test?allowPublicKeyRetrieval=true"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile-front
      target: run
    env_file: .env
    ports:
      - "80:80"
    environment:
      TOMCAT_PORT: "${TOMCAT_PORT:-8080}"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - "./docker/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro"
    network_mode: host
