### STAGE 1: Build ###
FROM maven:3-eclipse-temurin-11 AS build

COPY back/pom.xml .
COPY back/src src

RUN mvn clean install -DskipTests

### STAGE 2: Run ###
FROM eclipse-temurin:11-jre-alpine AS run
COPY --from=build target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
