# STAGE 1: Install
FROM node:16 AS install

WORKDIR /usr/src/app
COPY front/package*.json front/yarn.lock ./
RUN yarn install
COPY front/ .

# STAGE 2: Build
FROM install AS build

RUN yarn run ng build --configuration=production

# STAGE 3: Run
FROM nginx:stable-alpine AS run

COPY --from=build /usr/src/app/dist/yoga /usr/share/nginx/html
